server:
  address: 'tcp://0.0.0.0:9091/auth'

log:
  level: info

totp:
  issuer: karimi.me

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: karimi.me
      policy: one_factor
      resources:
        - '^/private(/.*)?$'
        - '^/g/.*$'

session:
  name: authelia_session
  secret: '${AUTHELIA_SESSION_SECRET}'
  expiration: 1h
  inactivity: 15m
  cookies:
    - domain: karimi.me
      authelia_url: https://karimi.me/auth
      default_redirection_url: https://karimi.me

storage:
  encryption_key: '${AUTHELIA_STORAGE_ENCRYPTION_KEY}'
  local:
    path: /var/lib/authelia/db.sqlite3

notifier:
  filesystem:
    filename: /var/lib/authelia/notification.txt

identity_validation:
  reset_password:
    jwt_secret: '${AUTHELIA_JWT_SECRET}'
